### ISSUE TITLE
torch.cat(per_task_running_loss[env_id]).mean().item(), IndexError: list index out of range

### ISSUE THREAD

**Issue by pussinmood** [PierreMarza/task_conditioned_adaptation#1]
i tried to reproduce this train.py by using ubuntu20.04 ,after some env issues solved  i start to train.but a issue happened like this :
![5381724303365_ pic_hd](https://github.com/user-attachments/assets/701cb1c4-ba3a-4a0b-b478-0a0144a90878)

**Comment by pussinmood** [comment]
it looks like the issue is about the train.py's line 206
 File "/root/autodl-tmp/src/run/train.py", line 206, in <module> torch.cat(per_task_running_loss[env_id]).mean().item(), IndexError: list index out of range

**Comment by pussinmood** [comment]
i hope you can give me some guide about this issue

**Comment by PierreMarza** [comment]
Hi, thank you for your interest in our work and for letting me know about this error. I have updated one line in train.py to consider the right number of training tasks when logging per-task losses (last commit: https://github.com/PierreMarza/task_conditioned_adaptation/commit/3c6dc05377eae15f6a1f5629b28b76571f878da3).

Please pull the updated code and let me know if it now runs properly!

**Comment by pussinmood** [comment]
thanks a lot，i will try this out～。～

**Comment by PierreMarza** [comment]
Is the problem now solved? If so, I will close this issue.

**Comment by PierreMarza** [comment]
The mentioned error was fixed. Fell free to reopen if needed.
